remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: "Coatings Northwest Inc"
collections:
  projects:
    output: true
    permalink: /projects/:title/
