title: "Coatings Northwest Inc"
url: "https://abrowncownow.github.io"
baseurl: "/coatings-nw"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project